### ISSUE TITLE
About backbone

### ISSUE THREAD

**Issue by DUT-CSJ** [linhanwang/SCCNet#5]
Hello, thank you for releasing your great work.
There is a question, in your paper, the backbone is trained 10 times smaller lr.
However, the backbone is frozen in your code.
Which setting is correct?
Looking forward to your reply.

**Comment by linhanwang** [comment]
Thank you for pointing out the inconsistency. At the begining, I followed SDM to finetune the backbone. But when I tried another dataset, I found out frozing the backbone is more robust. I use a parameter to control this. If you want to rerun the experiment on other dataset, you can compare the two methods easily.

**Comment by DUT-CSJ** [comment]
Thank you for replying!
