### ISSUE TITLE
I can't find the Cosine Similarity part

### ISSUE THREAD

**Issue by VCoklat** [linhanwang/SCCNet#6]
Hello... thank you for your work..
Your work really help my research, but i have one question based your description on the network architecture, we can see that you are using cosine similarity in cross matching module and self matching module. 
I tried to find this part in your code but couldn't find  it, can you help me tell me where is it?

**Comment by linhanwang** [comment]
Thank you for interested in my work. Please look at model/sccnet.py:56 (lines No. 56).

**Comment by VCoklat** [comment]
Thank you for your response :) So to confirm it did you combine the cosine similarity into Multilayer_correlation function?

**Comment by linhanwang** [comment]
Yes.
